version: '3.1'

services:
  db:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: ghanima_blog
      POSTGRES_PASSWORD: lovepisti123
    volumes:
      - pg-volume:/var/lib/postgresql/data  
    ports:
      - 5432:5432  

volumes:
  pg-volume: